#!/bin/bash
set -e

USERS_FILE="/etc/freeradius/3.0/users"

# Clear existing users file
echo "# Generated by entrypoint" > $USERS_FILE

# Loop through environment variables MAC1..MAC10 and VLAN1..VLAN10
for i in $(seq 1 10); do
  MAC_VAR="MAC${i}"
  VLAN_VAR="VLAN${i}"
  MAC="${!MAC_VAR}"
  VLAN="${!VLAN_VAR}"

  if [ -n "$MAC" ]; then
    echo "${MAC} Cleartext-Password := \"${MAC}\"" >> $USERS_FILE
    if [ -n "$VLAN" ]; then
      echo "    Tunnel-Type = VLAN," >> $USERS_FILE
      echo "    Tunnel-Medium-Type = IEEE-802," >> $USERS_FILE
      echo "    Tunnel-Private-Group-Id = ${VLAN}" >> $USERS_FILE
    fi
  fi
done

cat $USERS_FILE

exec "$@"

